#!/usr/bin/env ruby

output = 'www/lib/lodash/lodash.custom.min.js'
methods = %w(
  all
	any
  chain
  compact
  contains
  defaults
  each
  find
  flatten
  groupBy
  isEmpty
  isEqual
  keys
  map
  max
  memoize
  object
  pick
  pluck
  reduce
  reject
  select
  sortBy
  throttle
  value
)

# there is an undefined variable called freeGlobal which breaks "use strict", hence the iife
`lodash modern include=#{ methods.join(',') } --production --output #{ output } iife='!function(window,freeGlobal,undefined){%output%}(this)'`
